# ==========================================
# PHASE 1: CORE ENGINE & DATABASE CONNECTION
# ==========================================

# 1. Database Connection String
spring.datasource.url=jdbc:postgresql://localhost:5432/astracore_db
spring.datasource.username=postgres
spring.datasource.password=admin

# 2. Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Connection Pool Settings (Standard for Enterprise Apps)
spring.datasource.hikari.maximum-pool-size=10

# Server Port Setup
server.port=8080